<?php

namespace App\Services;

use App\Models\Studio;
use App\Models\PayrollPeriod;
use Carbon\Carbon;
use Exception;

class PayrollPeriodAutoGenerationService
{
    public function generatePeriodsForStudio($std_id, $targetDate = null)
    {
        $studio = Studio::findOrFail($std_id);

        if (!$studio->isPayrollAutoGenerated()) {
            throw new Exception('La generación automática está deshabilitada para este estudio');
        }

        $targetDate = $targetDate ? Carbon::parse($targetDate) : Carbon::now();

        // Leer configuración ACTUAL del estudio
        $currentInterval = $studio->getCurrentPayrollInterval();

        // Calcular período requerido según configuración actual
        $requiredPeriod = $this->calculateRequiredPeriod($currentInterval, $targetDate);

        // Verificar si ya existe
        $exists = PayrollPeriod::where('std_id', $std_id)
                    ->where('payroll_period_start_date', $requiredPeriod['start'])
                    ->where('payroll_period_end_date', $requiredPeriod['end'])
                    ->exists();

        if (!$exists) {
            return PayrollPeriod::create([
                'std_id' => $std_id,
                'payroll_period_start_date' => $requiredPeriod['start'],
                'payroll_period_end_date' => $requiredPeriod['end'],
                // COPIAR intervalo actual del estudio al período (para histórico)
                'payroll_period_interval' => $currentInterval,
                'is_auto_generated' => true,
                'payroll_period_smmlv' => $this->getCurrentSMMLV()
            ]);
        }

        return null;
    }

    /**
     * Generar período del mes actual específicamente
     */
    public function generateCurrentMonthPeriod($std_id)
    {
        return $this->generatePeriodsForStudio($std_id, Carbon::now()->startOfMonth());
    }

    public function generateNextPeriods($std_id, $count = 3)
    {
        $studio = Studio::findOrFail($std_id);
        $currentInterval = $studio->getCurrentPayrollInterval();
        $periods = [];

        // Empezar desde el siguiente período
        for ($i = 1; $i <= $count; $i++) {
            $targetDate = match($currentInterval) {
                'SEMANAL' => Carbon::now()->addWeeks($i),
                'QUINCENAL' => Carbon::now()->addWeeks($i * 2),
                'MENSUAL' => Carbon::now()->addMonths($i)->startOfMonth()
            };

            $period = $this->generatePeriodsForStudio($std_id, $targetDate);
            if ($period) {
                $periods[] = $period;
            }
        }

        return $periods;
    }

    private function calculateRequiredPeriod($interval, $date)
    {
        return match($interval) {
            'SEMANAL' => [
                'start' => $date->copy()->startOfWeek(Carbon::MONDAY)->format('Y-m-d'),
                'end' => $date->copy()->endOfWeek(Carbon::SUNDAY)->format('Y-m-d')
            ],
            'QUINCENAL' => [
                'start' => $date->day <= 15 ?
                    $date->copy()->startOfMonth()->format('Y-m-d') :
                    $date->copy()->day(16)->format('Y-m-d'),
                'end' => $date->day <= 15 ?
                    $date->copy()->day(15)->format('Y-m-d') :
                    $date->copy()->endOfMonth()->format('Y-m-d')
            ],
            'MENSUAL' => $this->calculateMonthlyPeriod($date),
            default => $this->calculateMonthlyPeriod($date)
        };
    }

    private function calculateMonthlyPeriod($date)
    {
        // Para MENSUAL, siempre generar el período del mes completo
        // Si la fecha objetivo es del mes actual o futuro, generar ese mes
        $targetMonth = $date->copy()->startOfMonth();

        return [
            'start' => $targetMonth->format('Y-m-d'),
            'end' => $targetMonth->copy()->endOfMonth()->format('Y-m-d')
        ];
    }

    private function getCurrentSMMLV()
    {
        // SMMLV Colombia 2025
        return 1400000;
    }
}