<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PayrollPeriod extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'payroll_periods';
    protected $primaryKey = 'payroll_period_id';

    protected $fillable = [
        'std_id',
        'payroll_period_start_date',
        'payroll_period_end_date',
        'payroll_period_state',
        'payroll_period_interval',
        'payroll_period_smmlv',
        'is_auto_generated'
    ];

    protected $casts = [
        'payroll_period_start_date' => 'date',
        'payroll_period_end_date' => 'date',
        'payroll_period_smmlv' => 'decimal:2',
        'is_auto_generated' => 'boolean'
    ];

    // Relationships
    public function studio()
    {
        return $this->belongsTo(Studio::class, 'std_id', 'std_id');
    }

    public function transactions()
    {
        return $this->hasMany(PayrollTransaction::class, 'payroll_period_id', 'payroll_period_id');
    }

    // Helper methods
    public function isOpen()
    {
        return $this->payroll_period_state === 'ABIERTO';
    }

    public function isClosed()
    {
        return $this->payroll_period_state === 'CERRADO';
    }

    public function isLiquidated()
    {
        return $this->payroll_period_state === 'LIQUIDADO';
    }

    public function close()
    {
        return $this->update(['payroll_period_state' => 'CERRADO']);
    }

    public function open()
    {
        return $this->update(['payroll_period_state' => 'ABIERTO']);
    }

    public function liquidate()
    {
        return $this->update(['payroll_period_state' => 'LIQUIDADO']);
    }

    public function isAutoGenerated()
    {
        return $this->is_auto_generated;
    }

    public function isManual()
    {
        return !$this->is_auto_generated;
    }

    // Scopes
    public function scopeForStudio($query, $studioId)
    {
        return $query->where('std_id', $studioId);
    }

    public function scopeOpen($query)
    {
        return $query->where('payroll_period_state', 'ABIERTO');
    }

    public function scopeClosed($query)
    {
        return $query->where('payroll_period_state', 'CERRADO');
    }

    public function scopeLiquidated($query)
    {
        return $query->where('payroll_period_state', 'LIQUIDADO');
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }
}
