<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Studio extends Model
{
    protected $table = 'studios';
    protected $primaryKey = 'std_id';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'std_id',
        'std_nit',
        'std_name',
        'std_address',
        'std_shifts',
        'std_percent',
        'std_liquidation_interval',
        'payroll_liquidation_interval',
        'payroll_auto_generate',
        'std_image',
        'std_bank_entity',
        'std_bank_account',
        'std_bank_account_type',
        //'std_ally',
        'std_ally_master_pays',
        'std_active',
        'std_discountstudio_eur',
        'std_discountstudio_usd',
        'std_discountmodel_eur',
        'std_discountmodel_usd',
        'user_id_owner',
        'std_rtefte',
        'city_id',
        'std_stdacc',
        'std_dispenser',
        'std_verification_digit',
        'std_manager_name',
        'std_manager_id',
        'std_manager_phone',
        'std_company_name'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
    ];


    public function banksAccounts()
    {
        return $this->hasMany(BankAccount::class, 'std_id', 'std_id')->whereNull('banks_accounts.deleted_at');
    }

    public function studiosRooms()
    {
        return $this->hasMany(StudioRoom::class, 'std_id', 'std_id')->whereNull('studios_rooms.deleted_at');
    }

    public function studiosShifts()
    {
        return $this->hasMany(StudioShift::class, 'std_id', 'std_id')->whereNull('studios_shifts.deleted_at');
    }

    public function studiosModels()
    {
        return $this->hasMany(StudioModel::class, 'std_id', 'std_id')->whereNull('studios_models.deleted_at');
    }

    public function payments()
    {
        return $this->hasMany(Payment::class, 'std_id', 'std_id')->whereNull('payments.deleted_at');
    }

    public function userOwner()
    {
        return $this->belongsTo(User::class, 'user_id_owner', 'user_id');
    }

    public function city()
    {
        return $this->belongsTo(City::class, 'city_id', 'city_id');
    }

    public function payrollPeriods()
    {
        return $this->hasMany(PayrollPeriod::class, 'std_id', 'std_id');
    }

    public function getCurrentPayrollInterval()
    {
        return $this->payroll_liquidation_interval ?? 'MENSUAL';
    }

    public function isPayrollAutoGenerated()
    {
        return $this->payroll_auto_generate ?? true;
    }

    /**
     * Calcula el dígito de verificación del NIT según el algoritmo estándar colombiano.
     *
     * @param string|null $nit El NIT a calcular (si no se proporciona, usa el del modelo)
     * @return string El dígito de verificación calculado (0-9)
     */
    public function calculateVerificationDigit($nit = null)
    {
        $nit = $nit ?? $this->std_nit;

        // Calcular solo si el nit no supera los 9 caracteres
        if (empty($nit) || strlen((string)$nit) > 9) {
            return "";
        }

        // Se limpia el Nit
        $nit = (string)$nit;
        $nit = str_replace(' ', '', $nit);  // Espacios
        $nit = str_replace(',', '', $nit);  // Comas
        $nit = str_replace('.', '', $nit);  // Puntos
        $nit = str_replace('-', '', $nit);  // Guiones

        // Se valida el nit
        if (!is_numeric($nit)) {
            return "";
        }

        // Procedimiento
        $vpri = [0, 3, 7, 13, 17, 19, 23, 29, 37, 41, 43, 47, 53, 59, 67, 71];
        $z = strlen($nit);

        $x = 0;
        for ($i = 0; $i < $z; $i++) {
            $y = (int)$nit[$i];
            $x += $y * $vpri[$z - $i];
        }

        $y = $x % 11;

        return $y > 1 ? 11 - $y : $y;
    }

    /**
     * Retorna el NIT del estudio con su dígito de verificación en formato: NIT-DV
     * Ejemplo: 901234567-8
     *
     * @return string
     */
    public function nitWithVerificationDigit()
    {
        if (empty($this->std_nit)) {
            return "";
        }

        $dv = $this->calculateVerificationDigit();
        return $this->std_nit . '-' . $dv;
    }

    /**
     * Alias del método nitWithVerificationDigit() para mayor claridad
     *
     * @return string
     */
    public function formattedNit()
    {
        return $this->nitWithVerificationDigit();
    }
}
